particles['x'] and ['y'] now always in grid units
nbia-astro/skeletor pull request #121
Opened 2017-03-13 21:10 UTC by tobson

I think it's best (least confusing) for the coordinates in the particle
array not to measured in different units in different parts of the code.

2017-03-13 21:10 UTC, tobson commented
@tberlok Let's do a rebase and merge if you agree with this change.

2017-03-13 21:22 UTC, tberlok requested changes
You should add the same change in particles.py line 119-120 then.

2017-03-13 21:22 UTC, tberlok commented on tests/test_fastwave.py
> +    ions['vx'] = ux_an(x, y, t=0)
I don't think this will work? What is x and y here?

2017-03-13 21:22 UTC, tberlok commented on tests/test_fastwave.py
> +    ions['vx'] = ux_an(x, y, t=0)
Nevermind the other comment. This should work, I guess.

2017-03-13 21:24 UTC, tberlok commented
I am going to bed, feel free to rebase and merge after adding the changes to the DensityPertubation class.

2017-03-13 21:53 UTC, tobson commented on tests/test_fastwave.py
> +    ions['vx'] = ux_an(x, y, t=0)
I changed lines 119-120. Thanks for catching that.

2017-03-13 21:57 UTC, tobson commented
It looks like you'll now need to update your review and approve of the changes before this can be merged. I can also dismiss your review, but that seems like poor form...

2017-03-14 07:28 UTC, tberlok approved these changes

2017-03-14 11:52 UTC, merged